### ISSUE TITLE
PERMISSION [FEATURE]

### ISSUE THREAD

**Issue by XenZify** [pablo3x6/SmallAdditions#3]
**Is your feature request related to a problem? Please describe.**
**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
There is no PROBLEM!

**Describe the solution you'd like**
**A clear and concise description of what you want to happen.**
I would like to see a permission node that acts as a wildnode or what ever they call it... This would be for the crop permission nodes. Instead of having to type out and give a group multiple perms for all the crops, you could just add a node like this, smalladd.crop.*
This would then give them all the farming nodes available. 
**Describe alternatives you've considered**
I never really considered anything?

**Additional context**
**Add any other context or screenshots about the feature request here.**
None

**Comment by pablo3x6** [comment]
So you want me to replace separate _smalladd.[crop]_ and add them under _smalladd.crops.[crop]_?

**Comment by pablo3x6** [comment]
Already added, will be included in the next update.
