### ISSUE TITLE
[BUG] All totems lost on death

### ISSUE THREAD

**Issue by Draxhax** [pablo3x6/SmallAdditions#4]
**Describe the bug**
Totem Death code erases all totems in player's inventory instead of just one.

**To Reproduce**
1. Start a Paper 1.15.2 server with this plugin (v1.4.6)
2. Place more than 1 totem of undying in your inventory. In my case, nearly my whole inventory was filled. I had a shield in my offhand and a sword in my main hand.
3. Die.
4. Observe that all totems are erased from inventory.

**Expected behavior**
Only 1 totem should be removed per death.

**Spigot/Bukkit/Paper (please complete the following information):**
 - git-Paper-162 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Additional context**
Checked your source. Bug is caused by using p.getInventory().remove() instead of p.getInventory().removeItem(). Neither will work if the meta has been changed on a totem, such as being renamed in an anvil, so iterating through the inventory may be necessary instead. There might be a different way to handle that, but I'm just not aware of it at the moment.

Per Spigot documentation:
[Inventory Documentation](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/Inventory.html#removeItem(org.bukkit.inventory.ItemStack...))

remove​(@NotNull ItemStack item) | Removes all stacks in the inventory matching the given stack.

removeItem​(@NotNull ItemStack... items) | Removes the given ItemStacks from the inventory.

**Comment by zbejas** [comment]
Will post an update. Thank you.

**Comment by zbejas** [comment]
The issue regarding item deletion has been fixed. The issue regarding the item meta change will be looked into further.
