### ISSUE TITLE
1.17 Update ?

### ISSUE THREAD

**Issue by BlinzHDS** [pablo3x6/SmallAdditions#9]
Hi there,

I just wanted to tell you that your mod looks amazing but unfortunately it isn't working yet on 1.17, I can't seem to find any other way to contact you so I'm asking it here : Are you going to update this mod (Small Additions) to 1.17 ?

Hopefully your answer will be positive, if else then it's ok, thanks for the work done !

**Comment by zbejas** [comment]
This plugin has tons of deprecated code. You can compile your own update using the newer craftbukkit for packets. Everything else should work the same.

I am planning on reworking the whole plugin so I can use something else than Minecraft packets, so the plugin could work on multiple versions, but this takes time and time is what I don't really have for side-projects with no monetary value.

**Comment by zbejas** [comment]
Hello. I would like to point out I have just started working on an improved version of this plugin.
I have mostly rewritten the code so it (in theory) works in most of the recent versions. Hasnt been well tested tho.

If you would like to check it out, click [here](https://github.com/pablo3x6/Grains).
You can download it [here](https://github.com/pablo3x6/Grains/releases).
